[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  
[[redirects]]
  from   = "/api/jwt-auth/v1/*"
  to     = "https://api.lasensazione.franklinoliveira.com/json/jwt-auth/v1/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/api/*"
  to     = "https://api.lasensazione.franklinoliveira.com/json/api/:splat"
  status = 200
  force  = true
